<?php
/**
 * Blocks -> Sitemap -> Render
 *
 */
if ( ! defined( 'ABSPATH' ) ) exit;


if ( ! function_exists( 'tepll_html_sitemap_get_html' ) || ! function_exists( 'tepll_html_sitemap_args_from_block_attributes' ) ) return '';

$tepll_html_sitemap_block_attributes = isset( $attributes ) && is_array( $attributes )
	? $attributes
	: array();

// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- markup from tepll_html_sitemap_get_html() uses esc_url/esc_html internally.
$tepll_html_sitemap_markup = tepll_html_sitemap_get_html( tepll_html_sitemap_args_from_block_attributes( $tepll_html_sitemap_block_attributes ) );

$tepll_html_sitemap_block_instance = ( isset( $block ) && $block instanceof WP_Block )
	? $block
	: null;

$tepll_html_sitemap_wrapper_class_list = array( 'tepll-html-sitemap' );
if (
	array_key_exists( 'show_list_bullets', $tepll_html_sitemap_block_attributes )
	&& empty( $tepll_html_sitemap_block_attributes['show_list_bullets'] )
) :
	$tepll_html_sitemap_wrapper_class_list[] = 'is-no-bullets';
endif;
$tepll_html_sitemap_wrapper_extra_attributes = array(
	'class' => implode( ' ', array_filter( $tepll_html_sitemap_wrapper_class_list ) ),
);

$tepll_html_sitemap_wrapper_attributes_string = function_exists( 'get_block_wrapper_attributes' )
	? get_block_wrapper_attributes( $tepll_html_sitemap_wrapper_extra_attributes, $tepll_html_sitemap_block_instance )
	: '';
if ( '' === trim( (string) $tepll_html_sitemap_wrapper_attributes_string ) ) :
	$tepll_html_sitemap_wrapper_attributes_string = 'class="wp-block-tepll-html-sitemap ' . esc_attr( $tepll_html_sitemap_wrapper_extra_attributes['class'] ) . '"';
endif;

?>
<div <?php echo $tepll_html_sitemap_wrapper_attributes_string; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Wrapper attrs generated by get_block_wrapper_attributes() or locally escaped fallback. ?>>
	<?php echo wp_kses_post( $tepll_html_sitemap_markup ); ?>
</div>
<?php
